config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages.urls")),
    path("issues/", include("issues.urls")),
]

issues/urls.py
from django.urls import path
from issues import views

urlpatterns = [
    path("", views.IssueListView.as_view(), name = "list"),
    path("new/", views.IssueCreateView.as_view(), name = "new"),
    path("<int:pk>/", views.IssueDetailView.as_view(), name = "detail"),
    path("<int:pk>/edit/", views.IssueUpdateView.as_view(), name = "edit"),
    path("<int:pk>/delete/", views.IssueDeleteView.as_view(), name = "delete"),
]

pages/urls.py
from django.urls import path
from pages import views

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("about/", views.AboutPageView.as_view(), name="about"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Team(models.Model):
    name = models.CharField(max_length=129)
    description = models.CharField(max_length=256)
    
    def __str__(self):
        return self.name
    
class Role(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=256)
    
    def __str__(self):
        return self.name
    
class CustomUser(AbstractUser):
    team = models.ForeignKey(
        Team,
        on_delete=models.CASCADE,
        blank=True, null=True   
    )
    role = models.ForeignKey(
        Role,
        on_delete=models.CASCADE,
        blank=True, null=True
    )
    

issues/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

# Create your models here.
class PriorityLevel(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=256)
    
    def __str__(self):
        return self.name
    
class Status(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=256)
    
    def __str__(self):
        return self.name

class Issue(models.Model):
    name = models.CharField(max_length=128)
    summary = models.CharField(max_length=256)
    description = models.TextField()
    reporter = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='reporter'
    )
    assignee = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='assignee'
    )
    priority = models.ForeignKey(
        PriorityLevel,
        on_delete=models.CASCADE,
    )
    status = models.ForeignKey(
        Status,
        on_delete=models.CASCADE
    )
    created_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("issues_detail", args=[self.id])

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm
)
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ("email", "role", "team")
        
class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = CustomUser
        fields = UserChangeForm.Meta.fields

accounts/views.py
from django.views.generic import CreateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

# Create your views here.
class SignUpView(CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")

issues/views.py
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.urls import reverse_lazy
from .models import Issue, Status
from accounts.models import CustomUser, Role, Team

class IssueListView(LoginRequiredMixin, ListView):
    template_name = "issues/list.html"
    model = Issue  
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        role = Role.objects.get(name="Product Owner")
        team_po = (
            CustomUser.objects
            .filter(team=user.team)
            .filter(role=role)
        )
        
        to_do = Status.objects.get(name="To-Do")
        context["to_do_list"] = (
            Issue.objects
            .filter(status=to_do)
            .filter(reporter=team_po[0])
            .order_by("created_on").reverse()
        )
        in_progress = Status.objects.get(name="In Progress")
        context["in_progress_list"] = (
            Issue.objects
            .filter(status=in_progress)
            .filter(reporter=team_po[0])
            .order_by("created_on").reverse()
        )
        completed = Status.objects.get(name="Completed")
        context["completed_list"] = (
            Issue.objects
            .filter(status=completed)
            .filter(reporter=team_po[0])
            .order_by("created_on").reverse()
        )
        return context

class IssueDetailView(UserPassesTestMixin, DetailView):
    model = Issue
    template_name = "issues/detail.html"
    
    def test_func(self):
        issue = self.get_object()
        if issue.status.name == "To-DO":
            return True
        elif issue.status.name == "In Progress":
            if (self.request.user.is_authenticated
                    and self.request.user == issue.reporter):
                return True
        elif (issue.status.name == "Completed"
                and self.request.user.is_authenticated):
            return True
        else:
            return False
    

class IssueCreateView(LoginRequiredMixin, CreateView):
    model = Issue
    template_name = "issues/new.html"
    fields = ["name", "summary", "description", "status"]
    
    def form_valid(self, form):
        form.instance.reporter = self.request.user
        return super().form_valid(form)
    
class IssueUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Issue
    template_name = "issues/edit.html"
    fields = ["name", "summary", "description", "status"]
    
    def test_func(self):
        issue = self.get_object()
        return issue.reporter == self.request.user
    
class IssueDeleteView(LoginRequiredMixin, DeleteView):
    model = Issue
    template_name = "issues/delete.html"
    success_url = reverse_lazy("list")
    
    def test_func(self):
        issue = self.get_object()
        return issue.reporter == self.request.user

pages/views.py
from django.views.generic import TemplateView


# Create your views here.
class HomePageView(TemplateView):
    template_name = "pages/home.html"

class AboutPageView(TemplateView):
    template_name = "pages/about.html"

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Issue Manager</title>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous">
        <link rel="stylesheet" href="/static/css/base.css">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">Home</a>
                <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">

                        <a class="nav-link" href="{% url 'list' %}">Issues</a>
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                        <a class="nav-link" href="#"></a>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container">
            {% block content %}{%endblock content %}
        </div>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous">
    </script>
    </body>
</html>

templates/issues/delete.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock title %}

{% block content %}
<h1>Delete Issue</h1>
<p>Are you sure you want to delete this issue?</p>
<pre>
    "{{ issue.name }}"
</pre>
<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Confirm">
</form>
{% endblock content %}

templates/issues/detail.html
{% extends 'base.html' %}

{% block title %}Issue Details{% endblock title %}

{% block content %}
<h1>{{ issue.name }}</h1>
<h3>{{ issue.summary }}</h3>
<p>{{ issue.description }}</p>
<small>Created By:{{ issue.reporter }} | On: {{ issue.created_on }}</small>
{% if user == is_authenticated %}
    {% if user == issue.reporter %}
    <br>
    <br>
    <a href="{% url 'edit' issue.id %}">Edit</a>
    {% endif %}
{% endif %}
{% endblock content %}

templates/issues/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit Issue{% endblock title %}

{% block content %}
<h1>Edit Issue</h1>
<form method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" class="btn btn-success" value="Edit">
</form>
{% endblock content %}

templates/issues/list.html
{% extends 'base.html' %}

{% block title %}Issues{% endblock title %}

{% block content %}
<h1>{{ name }}</h1>
{% for issue in issue_list %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ issue.name }}</h5>
        <h6 class="card-summary mb-2 mt-2 text-body-secondary">{{ issue.summary }}</h6>
        <p class="card-text">{{ issue.description|truncatechars:64 }}</p>

        <a href="{% url 'detail issue.id' %}">Details</a>
    </div>
</div>
<br>
{% endfor %}
{% endblock content %} 

templates/issues/new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}New Issue{% endblock title %}

{% block content %}
<h1>Create a new issue here</h1>
<form method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" class="btn btn-success" value="Create" >
</form>
{% endblock content %}

templates/pages/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock title %}

{% block content %}
<h1>About</h1>
<p>This is an issue manager board for a team to collaborate on and organize their day!</p>
{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<h1>Home</h1>
<p>Welcome to my homepage! What is going to be here is TBD.</p>
{% endblock content %}